//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string File { get; set; }
        public string Content { get; set; }
        public string Detail { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> Index { get; set; }
        public Nullable<int> Views { get; set; }
        public Nullable<int> GroupNewsId { get; set; }
        public string GroupName { get; set; }
        public string LinkDemo { get; set; }
        public string Description { get; set; }
        public string Keyword { get; set; }
        public Nullable<int> Ord { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
