//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string Image4 { get; set; }
        public string Image5 { get; set; }
        public string Content { get; set; }
        public string Detail { get; set; }
        public string Price { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> IsHot { get; set; }
        public Nullable<int> IsPopular { get; set; }
        public Nullable<int> Ord { get; set; }
        public string Description { get; set; }
        public string Keywords { get; set; }
        public Nullable<int> Active { get; set; }
        public string Price1 { get; set; }
    }
}
